// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// Migration locks require a stable session. Keep the application's pooled URL
// unchanged; use DIRECT_URL when supplied, or Neon's equivalent direct host.
let migrationUrl = process.env['DIRECT_URL'] || process.env['DATABASE_URL'];
if (!process.env['DIRECT_URL'] && migrationUrl) {
  const url = new URL(migrationUrl);
  if (
    url.hostname.endsWith('.neon.tech') &&
    url.hostname.includes('-pooler.')
  ) {
    url.hostname = url.hostname.replace('-pooler.', '.');
    migrationUrl = url.toString();
  }
}

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: migrationUrl,
  },
});
