export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard:read',
  ANALYTICS_READ: 'analytics:read',
  ALERTES_READ: 'alertes:read',
  SIGNALEMENT_READ: 'signalement:read',
  SIGNALEMENT_CREATE: 'signalement:create',
  SIGNALEMENT_UPDATE: 'signalement:update',
  SIGNALEMENT_SUBMIT: 'signalement:submit',
  SIGNALEMENT_VALIDATE: 'signalement:validate',
  SIGNALEMENT_REJECT: 'signalement:reject',
  ALERTE_MANAGE: 'alerte:manage',
  ALERTE_DETECT: 'alerte:detect',
  REGLE_MANAGE: 'regle:manage',
  USER_MANAGE: 'user:manage',
  CENTRE_MANAGE: 'centre:manage',
  ZONE_MANAGE: 'zone:manage',
  ROLE_MANAGE: 'role:manage',
  JOURNAL_READ: 'journal:read',
  SESSION_MANAGE: 'session:manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: readonly PermissionCode[] =
  Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  Administrateur: ALL_PERMISSIONS,
  'Responsable national': [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ALERTES_READ,
    PERMISSIONS.SIGNALEMENT_READ,
    PERMISSIONS.SIGNALEMENT_VALIDATE,
    PERMISSIONS.SIGNALEMENT_REJECT,
    PERMISSIONS.ALERTE_MANAGE,
    PERMISSIONS.ALERTE_DETECT,
    PERMISSIONS.REGLE_MANAGE,
    PERMISSIONS.JOURNAL_READ,
    PERMISSIONS.SESSION_MANAGE,
  ],
  'Responsable régional': [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ALERTES_READ,
    PERMISSIONS.SIGNALEMENT_READ,
    PERMISSIONS.SIGNALEMENT_CREATE,
    PERMISSIONS.SIGNALEMENT_UPDATE,
    PERMISSIONS.SIGNALEMENT_SUBMIT,
    PERMISSIONS.ALERTE_MANAGE,
  ],
  'Agent de santé': [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.SIGNALEMENT_READ,
    PERMISSIONS.SIGNALEMENT_CREATE,
    PERMISSIONS.SIGNALEMENT_UPDATE,
    PERMISSIONS.SIGNALEMENT_SUBMIT,
  ],
  Observateur: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ALERTES_READ,
    PERMISSIONS.SIGNALEMENT_READ,
  ],
};
